### PR TITLE
Project 2: Enumerable Methods

### PR DESCRIPTION
**Pull request by bmuhamood**
Milestone 1

1 - Added all the methods
2 - Fixed all errors
3 - Added all linters 
4 - I'm really unable to fix the below linter error and i'm unable to find answer on google and other stack-flows - Kindly request to advise.  

enumerables.rb:97:1: E: Lint/Syntax: unexpected token kEND
(Using Ruby 2.3 parser; configure using TargetRubyVersion parameter, under AllCops)
end

### CODE REVIEW

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Request changes :recycle:
### Hi @bmuhamood :clap: :clap:
#### Good job so far :muscle: however, the program is not working right now. Check my comments :point_down:

- **_All the methods should be inside a module and only the `multiply_els` should be outside of the module._**

#### _Note: About the linter error you mentioned; try and trace the closing `end` of each method and block_

**_Fix these errors and make sure all the methods return the expected/appropriate values as the original "Ruby Enumerable"_**

#### _Reviewed by Temitayo Adeleke._

**Comment by bmuhamood** [comment]
Milstone 2

- I have put All the methods inside a module and only the multiply_els outside of the module.

- Fixed errors and make sure all the methods return the expected/appropriate values as the original "Ruby Enumerable"

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @bmuhamood  :wave:
-
- Neither of the methods is passing any of my tests. Would you mind seeking help to help solve the glaring issues? 
- The readme as well lacks crucial information on how to clone and use the code.
- As for the linters errors, robocop, has not been configured properly in your repo. I would advise you to take a step back and try and schedule a meeting with a TSE  to have most of these issues sorted out.  Let me know what you think. Thank you!
##
Please makes changes and submit another review request.
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by bmuhamood** [comment]
Milestone 3. Fixing methods and rubocop - All App passed. 

- Fixed all linter errors by setting up rubocop correctly in my repo. 
- Tested all methods and passing. 
- Improved on my Readme file to make it look more professional
- Added Linters

**Review by maelfosso — APPROVED** [review]
# Congratulations :clap: 

You can merge it :+1: 

**PS** Please, in such situation, encapsulates your methods into a module declaration
```rb
module Enumerable
...
end
```

Good continuation :handshake: 

Mael FOSSO

**Comment by bmuhamood** [comment]
Thanks alot Mael and all TSEs who contributed in this project success.

**Pull request merged**
